server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/hm49
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    addresses:
    username:
    password:
    virtual-host:
    publisher-confirms: true
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.leyou.item.pojo