server:
  port: 8086
spring:
  application:
    name: leyou-sms
  rabbitmq:
    addresses:
    username:
    password:
    virtual-host:
leyou:
  sms:
    accessKeyId:
    accessKeySecret:
    signName:
    templateCode:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期