server:
  8008
spirng:
  application: leyou-cart
eureka:
  client:
    service-url:
      default-Zone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

leyou:
  jwt:
    cookieName: LY_TOKEN
    publicKeyPath: